Fixes personal cloud build and restores test on Travis
- Reverts #4014 (caused error TS7027: Unreachable code detected).
- Restores personal cloud test on Travis (reverts #4024).

Build should be back to normal!

Fixes #4018.